[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "HnS1rEzAGyt8sFdcDJGViVxJWugkDVJDBkHJTEsFn8qF"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "/home/priks/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
