[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.devnet.solana.com"

[devnet]
cluster = "devnet"
wallet = "/home/priks/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
